apiVersion: apps/v1
kind: Deployment
metadata:
  name: colab-backend 
  namespace: colab-app
  labels:
    app: colab-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colab-backend
  template:
    metadata:
      labels:
        app: colab-backend 
    spec:
      containers:
        - name: nginx
          image: cgr.dev/chainguard/nginx:latest

          env:
            - name: PORT
              value: "5000"
          envFrom:
            - secretRef:
                name: colab-backend-secret 

          volumeMounts:
            - name: backend-secrets-vol          
            mountPath: /app/secrets            
            readOnly: true                    

          volumes:
            - name: backend-secrets-vol
            secret:
            secretName: colab-backend-secret   
            defaultMode: 0400

          ports:
            - containerPort: 5000
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /
              port: 5000
          resources:
            limits:
              memory: "50Mi"
            requests:
              memory: "50Mi"
              cpu: "250m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
