apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: colab-backend-secret
  namespace: colab-app 
stringData:
  MONGODB_URL: ""
  JWT_SECRET_KEY: "" 
  GITHUB_CLIENTID: ""
  GITHUB_CLIENTSECRET: ""
  GITHUB_CLLBACKURL: ""
  GOOGLE_CLIENTID: ""
  GOOGLE_CLIENTSECRET: ""
  GOOGLE_CALBACKURL: ""
  GMAIL: "" 
  USER_PASSWORD: "" 
  HF_API_TOKEN: "" 



