apiVersion: v1
kind: Service
metadata:
  name: backend-service 
  labels:
    foo: service-label
  annotations:
    bar: service-annotation
spec:
  type: ClusterIP 
  selector:
    baz: pod-label
  ports:
    - protocol: TCP
      port: 5000 
      targetPort: 5000 
