apiVersion: v1
kind: Service
metadata:
  name: backend-service 
  namespace: colab-app
  labels:
    foo: service-label
  annotations:
    bar: service-annotation
spec:
  type: ClusterIP 
  selector:
    app: colab-backend 
  ports:
    - protocol: TCP
      port: 5000 
      targetPort: 5000 
