version: "3"

env:
  BORDER: double
  BORDER_FOREGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"
  NAMESPACE: colab-app

tasks:
  01-apply-Deployment:
    desc: "Apply Deployment configuration"
    cmds:
      - kubectl apply -f Deployment.yaml -n {{.NAMESPACE}}

  02-apply-clusterip-service:
    desc: "Apply the ClusterIP Service"
    cmds:
      - kubectl apply -f Service.yaml -n {{.NAMESPACE}}

  03-apply-secret-string-data:
    desc: "Apply Secret configuration"
    cmds:
      - kubectl apply -f Secret.yaml -n {{.NAMESPACE}}
