apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: 
  namespace: colab-app
stringData:
  # backend_baseurl: http://localhost:5000 
  INTERNAL_API_URL: https://colab-backend-v1-9-0.onrender.com
  NEXT_PUBLIC_BACKEND_URL: https://colab-backend-v1-9-0.onrender.com
  PORT: 3000


