apiVersion: v1
kind: Service
metadata:
  name: frontend-service 
  namespace: colab-app
  labels:
    foo: service-label
  annotations:
    bar: service-annotation
spec:
  type: ClusterIP 
  selector:
    app: colab-frontend 
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 3000 
